"""Bundled runnable examples: an OpenAPI document plus human-authored tasks.

Resource files live under ``callprobe/examples/<name>/`` so hatch ships them
inside the wheel and they can be turned into a suite with no checkout of this
repository and no network access. Their content must stay identical to the
canonical copies under the repository's top-level ``examples/`` directory;
``tests/test_examples.py`` asserts that byte-for-byte.
"""

from __future__ import annotations

import importlib.resources
import json
from typing import Any

import yaml

from .openapi import _Loader, _no_duplicate_keys, _reject_constant, check_json, generate_openapi_suite

EXAMPLES: dict[str, dict[str, Any]] = {
    "github-issues": {
        "openapi_file": "openapi.json",
        "description": "3 real GitHub issue/comment operations, GitHub's OpenAPI description",
        "provenance_files": ("LICENSE.md", "provenance.json"),
    },
    "support": {
        "openapi_file": "openapi.yaml",
        "description": "a small fictional order/refund API",
        "provenance_files": (),
    },
}


def _resource_dir(key: str):
    return importlib.resources.files("callprobe") / "examples" / key


def _resource_text(key: str, filename: str) -> str:
    return (_resource_dir(key) / filename).read_bytes().decode("utf-8-sig")


def _load_document(key: str, filename: str) -> Any:
    text = _resource_text(key, filename)
    if filename.endswith(".json"):
        data = json.loads(text, object_pairs_hook=_no_duplicate_keys, parse_constant=_reject_constant)
    else:
        data = yaml.load(text, Loader=_Loader)  # noqa: S506 - restricted SafeLoader subclass
    check_json(data)
    return data


def _task_count(key: str) -> int:
    doc = yaml.safe_load(_resource_text(key, "tasks.yaml")) or {}
    return len(doc.get("tasks") or [])


def list_examples() -> list[tuple[str, int, str]]:
    """(name, active task count, one-line description), sorted by name."""
    return [(key, _task_count(key), EXAMPLES[key]["description"]) for key in sorted(EXAMPLES)]


def _readme(key: str, active_tasks: int) -> str:
    lines = [
        f"# {key} example suite",
        "",
        f"Generated by `callprobe init --example {key}`. This suite ships with "
        f"{active_tasks} human-authored task(s), already active: no OpenAPI or "
        "task editing is required before `callprobe validate` and `callprobe run`.",
        "",
        "See `import-report.json` for the imported tool operations and diagnostics.",
        "",
        "Arguments are grouped under `path`, `query`, and `body` as defined in",
        "`tools.yaml`. Callprobe evaluates model tool calls; it does not execute",
        "the API operations. Running the suite requires a model endpoint.",
    ]
    if EXAMPLES[key]["provenance_files"]:
        lines += [
            "",
            "The OpenAPI document is a small projection of a third-party OpenAPI "
            "description. See `LICENSE.md` for its license and `provenance.json` "
            "for the source URL, revision, and hash.",
        ]
    return "\n".join(lines) + "\n"


def generate_example_suite(key: str, name: str):
    """Build suite files for a bundled example, ready to run with no edits.

    Reuses the OpenAPI importer to generate tools/suite scaffolding, then
    replaces the draft ``tasks.yaml`` with the bundled authored tasks.
    Returns (files, result) like ``generate_openapi_suite``.
    """
    if key not in EXAMPLES:
        raise ValueError(f"unknown example {key!r}; choose from: {', '.join(sorted(EXAMPLES))}")
    info = EXAMPLES[key]
    document = _load_document(key, info["openapi_file"])
    files, result = generate_openapi_suite(document, name, skip_unsupported=False)
    files["tasks.yaml"] = _resource_text(key, "tasks.yaml")
    files["README.md"] = _readme(key, _task_count(key))
    for filename in info["provenance_files"]:
        files[filename] = _resource_text(key, filename)
    return files, result
